### PR TITLE
Changed the constant_time_compare import from itsdangerous lib

### LINKED ISSUE #49: Change the constant_time_compare import from itsdangerous lib

### PR DESCRIPTION
**Pull request by Riverfount**
Close #49

### CODE REVIEW

**Comment by mikeboers** [comment]
Thanks for this.

**Comment by jcbollinger** [comment]
This doesn't seem to be working with itsdangerous 2.1.2:
```
ImportError: cannot import name 'constant_time_compare' from 'itsdangerous' (.../python3.9/site-packages/itsdangerous/__init__.py)

During handling of the above exception, another exception occurred:
...
ModuleNotFoundError: No module named 'itsdangerous._compat'

```
